# Generated by Django 5.2 on 2025-06-23 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_producto_descripcion_producto_precio_venta_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='precio_venta',
        ),
    ]
