# Generated by Django 5.2 on 2025-06-24 21:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0005_producto_precio_venta'),
        ('proveedores', '0003_alter_proveedor_codigo_alter_proveedor_telefono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='productos', to='proveedores.proveedor'),
        ),
    ]
