# Generated by Django 5.2 on 2025-06-19 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zonas', '0002_alter_zona_municipio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zona',
            name='municipio',
            field=models.CharField(max_length=100),
        ),
    ]
