# Generated by Django 5.2 on 2025-06-24 21:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0003_empleado_apellido_alter_empleado_direccion'),
        ('inventario', '0006_alter_producto_proveedor'),
        ('zonas', '0003_alter_zona_municipio'),
    ]

    operations = [
        migrations.AddField(
            model_name='zona',
            name='bodega',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, related_name='zonas', to='inventario.bodega'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='zona',
            name='cobrador_asignado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='zonas', to='empleados.empleado'),
        ),
    ]
