# Generated by Django 5.2 on 2025-06-19 03:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_alter_bodega_municipio_alter_inventariobodega_bodega_and_more'),
        ('zonas', '0003_alter_zona_municipio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zona',
            name='municipio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zonas', to='inventario.municipio'),
        ),
    ]
