# Generated by Django 5.2 on 2025-05-29 03:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0004_delete_zonacobro'),
        ('empleados', '0003_empleado_apellido_alter_empleado_direccion'),
        ('inventario', '0002_alter_bodega_municipio_alter_inventariobodega_bodega_and_more'),
        ('ventas', '0002_alter_venta_cliente_alter_ventadetalle_producto_and_more'),
        ('zonas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venta',
            name='total',
        ),
        migrations.AddField(
            model_name='venta',
            name='municipio',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='inventario.municipio'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='venta',
            name='zona',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='zonas.zona'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='venta',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clientes.cliente'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='vendedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='empleados.empleado'),
        ),
    ]
