# Generated by Django 5.2 on 2025-06-03 23:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_alter_bodega_municipio_alter_inventariobodega_bodega_and_more'),
        ('ventas', '0003_remove_venta_total_venta_municipio_venta_zona_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='ventadetalle',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalles', to='inventario.producto'),
        ),
    ]
