# Generated by Django 5.2 on 2025-05-26 04:52

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        ('empleados', '0001_initial'),
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cuota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_vencimiento', models.DateField()),
                ('pagado', models.BooleanField(default=False)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_pagado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_pago', models.DateTimeField(default=django.utils.timezone.now)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('cobrador', models.ForeignKey(limit_choices_to={'rol': 'cobrador'}, on_delete=django.db.models.deletion.CASCADE, to='empleados.empleado')),
                ('cuota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cobros.cuota')),
            ],
        ),
        migrations.CreateModel(
            name='RutaCobro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('fecha_programada', models.DateField()),
                ('cobrador', models.ForeignKey(limit_choices_to={'rol': 'cobrador'}, on_delete=django.db.models.deletion.CASCADE, to='empleados.empleado')),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.municipio')),
                ('zona', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clientes.zonacobro')),
            ],
        ),
    ]
