# Generated by Django 5.2 on 2025-05-29 02:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_alter_cliente_zona'),
        ('cobros', '0001_initial'),
        ('empleados', '0003_empleado_apellido_alter_empleado_direccion'),
        ('zonas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuota',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clientes.cliente'),
        ),
        migrations.AlterField(
            model_name='pago',
            name='cobrador',
            field=models.ForeignKey(limit_choices_to={'tipo': 'cobrador'}, on_delete=django.db.models.deletion.CASCADE, to='empleados.empleado'),
        ),
        migrations.AlterField(
            model_name='pago',
            name='cuota',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cobros.cuota'),
        ),
        migrations.AlterField(
            model_name='rutacobro',
            name='cobrador',
            field=models.ForeignKey(limit_choices_to={'tipo': 'cobrador'}, on_delete=django.db.models.deletion.PROTECT, to='empleados.empleado'),
        ),
        migrations.AlterField(
            model_name='rutacobro',
            name='zona',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='zonas.zona'),
        ),
    ]
