# Generated by Django 5.2 on 2025-05-29 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empleado',
            name='municipio',
        ),
        migrations.RemoveField(
            model_name='empleado',
            name='rol',
        ),
        migrations.RemoveField(
            model_name='empleado',
            name='apellido',
        ),
        migrations.AddField(
            model_name='empleado',
            name='direccion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='empleado',
            name='telefono',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='empleado',
            name='tipo',
            field=models.CharField(choices=[('vendedor', 'Vendedor'), ('cobrador', 'Cobrador')], default='', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='empleado',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='Municipio',
        ),
        migrations.DeleteModel(
            name='Rol',
        ),
    ]
