# Generated by Django 5.2 on 2025-05-29 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0002_remove_empleado_municipio_remove_empleado_rol_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='apellido',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='empleado',
            name='direccion',
            field=models.CharField(blank=True, null=True),
        ),
    ]
