# Generated by Django 5.2 on 2025-05-28 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='apellido',
            field=models.CharField(default='', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cliente',
            name='codeudor',
            field=models.CharField(default='', max_length=150),
            preserve_default=False,
        ),
    ]
