# Generated by Django 5.2 on 2025-05-29 02:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_alter_cliente_zona'),
        ('cobros', '0002_alter_cuota_cliente_alter_pago_cobrador_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ZonaCobro',
        ),
    ]
