# Generated by Django 5.2 on 2025-06-18 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Proveedores',
            new_name='Proveedor',
        ),
    ]
